# Generated by Django 4.0.3 on 2022-03-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('male', models.BooleanField()),
                ('birthday', models.DateField()),
                ('birthplace', models.TextField()),
                ('relation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.IntegerField()),
                ('date_of_record', models.DateField(auto_now_add=True)),
                ('initiator_department', models.TextField()),
                ('initiator_post', models.TextField()),
                ('initiator_rank', models.CharField(max_length=255)),
                ('initiator_surname', models.CharField(max_length=255)),
                ('initiator_name', models.CharField(max_length=255)),
                ('initiator_patronymic', models.CharField(max_length=255)),
                ('executor_department', models.TextField()),
                ('executor_post', models.TextField()),
                ('executor_rank', models.CharField(max_length=255)),
                ('executor_surname', models.CharField(max_length=255)),
                ('executor_name', models.CharField(max_length=255)),
                ('executor_patronymic', models.CharField(max_length=255)),
                ('event_number', models.CharField(max_length=255)),
                ('formation_date', models.DateField()),
                ('article', models.CharField(max_length=255)),
                ('plot', models.TextField()),
                ('incident_date', models.DateField()),
                ('address', models.TextField()),
                ('relative_search', models.BooleanField(default=False)),
                ('reg_date', models.DateField()),
            ],
        ),
    ]
