# Generated by Django 4.0.4 on 2022-06-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='', max_length=10, verbose_name='Статья')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статья УК РФ',
                'verbose_name_plural': 'Статьи УК РФ',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Национальность')),
                ('group', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Национальность',
                'verbose_name_plural': 'Национальность',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('Мужской', 'Male'), ('Женский', 'Female')], default='Мужской', max_length=7, verbose_name='Пол')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('birthplace', models.TextField(blank=True, default='Не установлено', null=True, verbose_name='Место рождения')),
                ('relation', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Степень родства')),
                ('passport_series', models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Номер паспорта')),
                ('pasport_date_of_issue', models.DateField(blank=True, default=None, null=True, verbose_name='Дата выдачи')),
                ('pasport_division_code', models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='Код подразделения')),
                ('pasport_division_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Подразделение')),
                ('inn', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='ИНН')),
                ('snils', models.CharField(blank=True, default=None, max_length=11, null=True, verbose_name='СНИЛС')),
                ('victim', models.BooleanField(blank=True, default=False, null=True, verbose_name='Потерпевший')),
                ('citizenship', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Гражданство')),
            ],
            options={
                'verbose_name': 'Лица на проверку',
                'verbose_name_plural': 'Лица на проверку',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.IntegerField(blank=True, default=None, null=True, verbose_name='Регистрационный номер')),
                ('date_of_record', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('initiator_department', models.TextField(verbose_name='Подразделение (Инициатор)')),
                ('initiator_post', models.TextField(verbose_name='Должность (Инициатор)')),
                ('initiator_rank', models.CharField(max_length=255, verbose_name='Сп. звание (Инициатор)')),
                ('initiator_surname', models.CharField(max_length=255, verbose_name='Фамилия (Инициатор)')),
                ('initiator_name', models.CharField(max_length=255, verbose_name='Имя (Инициатор)')),
                ('initiator_patronymic', models.CharField(max_length=255, verbose_name='Отчество (Инициатор)')),
                ('executor_department', models.TextField(verbose_name='Подразделение (Исполнитель)')),
                ('executor_post', models.TextField(verbose_name='Должность (Исполнитель)')),
                ('executor_rank', models.CharField(max_length=255, verbose_name='Сп. звание (Исполнитель)')),
                ('executor_surname', models.CharField(max_length=255, verbose_name='Фамилия (Исполнитель)')),
                ('executor_name', models.CharField(max_length=255, verbose_name='Имя (Исполнитель)')),
                ('executor_patronymic', models.CharField(max_length=255, verbose_name='Отчество (Исполнитель)')),
                ('event_number', models.CharField(max_length=255, verbose_name='Материалы')),
                ('formation_date', models.DateField(verbose_name='Дата регистрации материалов')),
                ('article', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статья УК РФ')),
                ('plot', models.TextField(blank=True, default=None, null=True, verbose_name='Событие')),
                ('incident_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата происшествия')),
                ('address', models.TextField(blank=True, default=None, null=True, verbose_name='Адрес места происшествия')),
                ('relative_search', models.BooleanField(default=False, verbose_name='Родственный поиск')),
                ('reg_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Исследования',
                'verbose_name_plural': 'Исследования',
                'ordering': ['-date_of_record'],
            },
        ),
    ]
