# Generated by Django 4.0.3 on 2022-03-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='reg_number',
            field=models.IntegerField(null=True),
        ),
    ]
