# Generated by Django 4.0.4 on 2022-06-27 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Принял эксперт'),
        ),
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.nationality', verbose_name='Национальность'),
        ),
        migrations.AddField(
            model_name='person',
            name='research',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='research.research', verbose_name='Исследование'),
        ),
        migrations.AddConstraint(
            model_name='research',
            constraint=models.UniqueConstraint(fields=('reg_number', 'reg_date'), name='unique research'),
        ),
    ]
