# Generated by Django 4.0.3 on 2022-03-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_research_reg_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='relation',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='research',
            name='address',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='research',
            name='article',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='research',
            name='incident_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='research',
            name='plot',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='research',
            name='reg_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='research',
            name='reg_number',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
