# Generated by Django 4.0.3 on 2022-03-20 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_alter_person_relation_alter_research_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='research',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='research.research'),
        ),
    ]
