# Generated by Django 4.0.3 on 2022-03-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_alter_person_research'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='relation',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
