# Generated by Django 4.0.3 on 2022-03-22 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_alter_person_relation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Лица на проверку', 'verbose_name_plural': 'Лица на проверку'},
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name': 'Исследования', 'verbose_name_plural': 'Исследования'},
        ),
    ]
