# Generated by Django 4.0.3 on 2022-03-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_alter_person_options_alter_research_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='male',
            field=models.CharField(choices=[(1, 'Мужской'), (0, 'Женский')], max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
    ]
