# Generated by Django 4.0.3 on 2022-03-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_alter_person_male_alter_person_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='male',
            field=models.BooleanField(),
        ),
    ]
