# Generated by Django 4.0.3 on 2022-04-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_alter_person_male'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='reg_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='reg_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
