# Generated by Django 4.0.3 on 2022-04-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_alter_research_reg_date_alter_research_reg_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='male',
            field=models.BooleanField(choices=[(True, 'Мужской'), (False, 'Женский')]),
        ),
    ]
