# Generated by Django 4.0.3 on 2022-04-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_alter_person_male'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Статьи УК РФ',
                'verbose_name_plural': 'Статьи УК РФ',
            },
        ),
    ]
