# Generated by Django 4.0.3 on 2022-04-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0014_remove_person_male_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Male'), ('Женский', 'Female')], default='Мужской', max_length=7),
        ),
    ]
