# Generated by Django 4.0.3 on 2022-04-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0015_alter_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='article',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='incident_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='plot',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
