version: '3.8'

services:
  web:
    restart: always
    build: 
      context: ./dnaresearch
      dockerfile: Dockerfile.prod
    command: gunicorn dnaresearch.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/dnaresearch/web/staticfiles
      - media_volume:/home/dnaresearch/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    restart: always
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static_volume:/home/dnaresearch/web/staticfiles
      - media_volume:/home/dnaresearch/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: