version: '3.7'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  web:
    build: .
    command: python /usr/src/dnaresearch/manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/usr/src/dnaresearch
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data: