###########
# BUILDER #
###########

# pull official base image
FROM python:3.9.6-alpine as builder

# set work directory
WORKDIR /usr/src/dnaresearch

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev tk dos2unix

# lint
RUN pip install --upgrade pip
RUN pip install flake8==3.9.2
COPY . .
RUN flake8 --ignore=E501,F401 ./dnaresearch

# install dependencies
COPY ./requirements.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/dnaresearch/wheels -r requirements.txt


#########
# FINAL #
#########

# pull official base image
FROM python:3.9.6-alpine

# create directory for the app user
RUN mkdir -p /home/dnaresearch

# create the app user
RUN addgroup -S dnaresearch && adduser -S dnaresearch -G dnaresearch

# create the appropriate directories
ENV HOME=/home/dnaresearch
ENV APP_HOME=/home/dnaresearch/web
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/staticfiles
RUN mkdir $APP_HOME/mediafiles
WORKDIR $APP_HOME

# install dependencies
RUN apk update && apk add libpq tk
COPY . .
COPY --from=builder /usr/src/dnaresearch/wheels /wheels
COPY --from=builder /usr/src/dnaresearch/requirements.txt .
RUN pip install --no-cache /wheels/*

# copy entrypoint.prod.sh
COPY ./entrypoint.prod.sh .
RUN sed -i 's/\r$//g'  $APP_HOME/entrypoint.prod.sh
RUN chmod +x  $APP_HOME/entrypoint.prod.sh

# copy project
COPY . $APP_HOME

# chown all the files to the app user
RUN chown -R dnaresearch:dnaresearch $APP_HOME

# change to the app user
USER dnaresearch

# run entrypoint.prod.sh
ENTRYPOINT ["/home/dnaresearch/web/entrypoint.prod.sh"]